version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running tests...
      - pytest --maxfail=1 --disable-warnings -q

  build:
    commands:
      - echo Build successful. Preparing artifact...

artifacts:
  files:
    - '**/*'
